### ISSUE TITLE
Bookmarks search not working in OC8

### ISSUE THREAD

**Issue by PeGa** [nextcloud/bookmarks#131]
Hi, when I go to my bookmarks app and in the top right corner of the screen I try to search, in owncloud logs this appears:

```
{"reqId":"7f27997e0d1a4269fbcad40e11c207a2",
"remoteAddr":"190.31.13.117",
"app":"index",
"message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT * FROM (SELECT *,
 (select array_to_string(array_agg(\\\"tag\\\"),
',
')\\n\\t\\t\\t\\tfrom \\\"oc_bookmarks_tags\\\" where \\\"bookmark_id\\\" = \\\"b2\\\".\\\"id\\\") as \\\"tags\\\"\\n\\t\\t\\t\\tFROM \\\"oc_bookmarks\\\" \\\"b2\\\"\\n\\t\\t\\t\\tWHERE \\\"user_id\\\" = ? ) as \\\"b\\\" WHERE true  AND lower(url || title || description || ifnull(tags,
'') ) like ?  ORDER BY id DESC  LIMIT 10 OFFSET 0' with params [\\\"pega\\\",
 \\\"%django%\\\"]:\\n\\nSQLSTATE[42883]: Undefined function: 7 ERROR:  function ifnull(text,
 unknown) does not exist\\nLINE 4: ...RE true  AND lower(url || title || description || ifnull(tag...\\n                                                             ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\",
\"Code\":0,
\"Trace\":\"#0 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...',
 Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver),
 Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException),
 'SELECT * FROM (...',
 Array)\\n#2 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/lib\\\/private\\\/db\\\/statementwrapper.php(63): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/apps\\\/bookmarks\\\/controller\\\/lib\\\/bookmarks.php(177): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/apps\\\/bookmarks\\\/controller\\\/lib\\\/search.php(42): OCA\\\\Bookmarks\\\\Controller\\\\Lib\\\\Bookmarks::findBookmarks('pega',
 Object(OC\\\\AppFramework\\\\Db\\\\Db),
 0,
 'id',
 'django',
 false)\\n#5 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/lib\\\/private\\\/search.php(66): OCA\\\\Bookmarks\\\\Controller\\\\Lib\\\\Search->search('django')\\n#6 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/core\\\/search\\\/ajax\\\/search.php(53): OC\\\\Search->searchPaged('django',
 Array,
 1,
 30)\\n#7 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/mydomain...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_166453',
 Array)\\n#10 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/core\\\/search')\\n#11 \\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",
\"File\":\"\\\/var\\\/www\\\/mydomain.com\\\/www\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",
\"Line\":91}",
"level":4,
"time":"2015-03-03T07:27:25+00:00"}
```

While this happens, my bookmarks list does not modify (as I never tried to search in first place) and a spinning icon appears down below saying "Searching other places..."

Seeing the logs seems like something I almost I could fix, but I don't quite understand what does this mean:

```
Undefined function: 7 ERROR:  function ifnull(text,
 unknown) does not exist\\nLINE 4: ...RE true  AND lower(url || title || description || ifnull(tag...\\n                                                             ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\",
\"Code\":0,
\"Trace\":\"#0 
```

Thanks in advance.

**Comment by mcmurphyrp** [comment]
Hi guys, I just wonder why I do not see any search box at all, in the top right corner, using latest relaease of bookamrks with OC 8.1.3.

**Comment by blizzz** [comment]
The search system was changed. I was looking for some time into it, so we definitely need to adjust. It seems we need/should provide a search plugin like files or mail app are doing. And then filter our list. 

Anybody interested to work on it?

**Comment by Chouchen** [comment]
:+1: it's a must need and a priority.

**Comment by marcelklehr** [comment]
Check out and feel free to test #347 :)
