### ISSUE TITLE
Log file is flooded because of Bookmarks without favicon

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/bookmarks#556]
The log file is flooded when websites have no favicon. 

### Steps to reproduce
Add a website without bookmark to the list of bookmarks

### Expected behaviour
Ignore missing favicons without warning entry in the logfile

### Actual behaviour
One log file entry for each missing favicon.

### Server configuration

**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
13
**Bookmarks version:** (see Nextcloud apps page)
0.12.1

#### Nextcloud log (data/nextcloud.log)
```
`
{"reqId":"W4bZ9FUNihUAADtk-SYAAAAF","level":2,"time":"2018-08-29T17:37:57+00:00","remoteAddr":"37.201.195.52","user":"dartcafe","app":"bookmarks","method":"GET","url":"\/index.php\/apps\/bookmarks\/bookmark\/233\/favicon","message":"GuzzleHttp\\Exception\\ClientException: Client error response [url] https:\/\/www.heise.de\/security\/dienste\/Der-Scan-869077.html [status code] 404 [reason phrase] Not Found in \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/Exception\/RequestException.php:89\nStack trace:\n
#0 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/Subscriber\/HttpError.php(32): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Message\\Request), Object(GuzzleHttp\\Message\\Response))\n
#1 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/Event\/Emitter.php(108): GuzzleHttp\\Subscriber\\HttpError->onComplete(Object(GuzzleHttp\\Event\\CompleteEvent), 'complete')\n
#2 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/RequestFsm.php(91): GuzzleHttp\\Event\\Emitter->emit('complete', Object(GuzzleHttp\\Event\\CompleteEvent))\n
#3 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n
#4 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/react\/promise\/src\/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)\n
#5 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/ringphp\/src\/Future\/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n
#6 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/Message\/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\n
#7 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/RequestFsm.php(134): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\n
#8 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n
#9 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/react\/promise\/src\/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)\n
#10 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/ringphp\/src\/Future\/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n
#11 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/Message\/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\n
#12 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/RequestFsm.php(134): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\n
#13 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/Client.php(165): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n
#14 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/guzzlehttp\/guzzle\/src\/Client.php(125): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Message\\Request))\n
#15 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/marcelklehr\/link-preview\/src\/Readers\/HttpReader.php(95): GuzzleHttp\\Client->get('http:\/\/www.heis...', Array)\n
#16 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/marcelklehr\/link-preview\/src\/Parsers\/BaseParser.php(65): Marcelklehr\\LinkPreview\\Readers\\HttpReader->readLink(Object(Marcelklehr\\LinkPreview\\Models\\Link))\n
#17 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/marcelklehr\/link-preview\/src\/Parsers\/HtmlParser.php(111): Marcelklehr\\LinkPreview\\Parsers\\BaseParser->readLink(Object(Marcelklehr\\LinkPreview\\Models\\Link))\n
#18 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/vendor\/marcelklehr\/link-preview\/src\/Client.php(62): Marcelklehr\\LinkPreview\\Parsers\\HtmlParser->parseLink(Object(Marcelklehr\\LinkPreview\\Models\\Link))\n
#19 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/controller\/lib\/linkexplorer.php(23): Marcelklehr\\LinkPreview\\Client->getPreview('general')\n
#20 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/controller\/lib\/previews\/defaultpreviewservice.php(73): OCA\\Bookmarks\\Controller\\Lib\\LinkExplorer->get('http:\/\/www.heis...')\n
#21 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/controller\/lib\/previews\/faviconpreviewservice.php(45): OCA\\Bookmarks\\Controller\\Lib\\Previews\\DefaultPreviewService->scrapeUrl('http:\/\/www.heis...')\n
#22 \/www\/htdocs\/nextcloud\/apps\/bookmarks\/controller\/rest\/internalbookmarkcontroller.php(243): OCA\\Bookmarks\\Controller\\Lib\\Previews\\FaviconPreviewService->getImage(Array)\n
#23 [internal function]: OCA\\Bookmarks\\Controller\\Rest\\InternalBookmarkController->getBookmarkFavicon(233)\n
#24 \/www\/htdocs\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(161): call_user_func_array(Array, Array)\n
#25 \/www\/htdocs\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Bookmarks\\Controller\\Rest\\InternalBookmarkController), 'getBookmarkFavi...')\n
#26 \/www\/htdocs\/nextcloud\/lib\/private\/AppFramework\/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Bookmarks\\Controller\\Rest\\InternalBookmarkController), 'getBookmarkFavi...')\n
#27 \/www\/htdocs\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('InternalBookmar...', 'getBookmarkFavi...', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n
#28 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n
#29 \/www\/htdocs\/nextcloud\/lib\/private\/Route\/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n
#30 \/www\/htdocs\/nextcloud\/lib\/base.php(999): OC\\Route\\Router->match('\/apps\/bookmarks...')\n
#31 \/www\/htdocs\/nextcloud\/index.php(42): OC::handleRequest()\n
#32 {main}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.5.2"}`

**Comment by marcelklehr** [comment]
> Isn't it possible to omit these warning messages? Maybe classifying them as debug?

You're probably right. It's not something that is outright exceptional.

**Comment by marcelklehr** [comment]
Fixed now :)
